export const CurrencyEnum = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
  CAD: 'CAD',
  AUD: 'AUD',
  CHF: 'CHF',
  JPY: 'JPY',
  SEK: 'SEK',
  NOK: 'NOK',
  DKK: 'DKK',
  CZK: 'CZK',
  PLN: 'PLN',
  HUF: 'HUF',
  RON: 'RON',
  BGN: 'BGN',
  RUB: 'RUB',
  INR: 'INR',
  BRL: 'BRL',
  ZAR: 'ZAR',
  MXN: 'MXN',
  CNY: 'CNY',
  HKD: 'HKD',
  TWD: 'TWD',
  SGD: 'SGD',
  THB: 'THB',
  TRY: 'TRY',
  RSD: 'RSD',
  HRK: 'HRK',
  ISK: 'ISK',
  BAM: 'BAM'
} as const;
export type CurrencyEnum = (typeof CurrencyEnum)[keyof typeof CurrencyEnum];
