/**
 * Generated by ForkLaunch
 * File: registrations.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */
import {
  function_,
  number,
  SchemaValidator,
  string,
  type
} from '@repro-app/core';
import { metrics } from '@repro-app/monitoring';
import { RedisTtlCache } from '@forklaunch/infrastructure-redis';
import { OpenTelemetryCollector } from '@forklaunch/core/http';
import {
  ComplianceDataService,
  createConfigInjector,
  getEnvVar,
  Lifetime,
  RetentionService
} from '@forklaunch/core/services';
import {
  FieldEncryptor,
  wrapEmWithTenantContext
} from '@forklaunch/core/persistence';
import { BullMqWorkerConsumer } from '@forklaunch/implementation-worker-bullmq/consumers';
import { BullMqWorkerProducer } from '@forklaunch/implementation-worker-bullmq/producers';
import { BullMqWorkerSchemas } from '@forklaunch/implementation-worker-bullmq/schemas';
import { BullMqWorkerOptions } from '@forklaunch/implementation-worker-bullmq/types';
import {
  EncryptingWorkerProducer,
  withDecryption,
  withDecryptionFailureHandler
} from '@forklaunch/interfaces-worker/interfaces';
import {
  type EncryptedEventEnvelope,
  WorkerProcessFunction,
  WorkerFailureHandler
} from '@forklaunch/interfaces-worker/types';
import type { MyworkrEventRecord } from './domain/types/myworkrEventRecord.types';
import { BaseMyworkrService } from './domain/services/myworkr.service';
//! instantiates the config injector
const configInjector = createConfigInjector(SchemaValidator(), {
  SERVICE_METADATA: {
    lifetime: Lifetime.Singleton,
    type: {
      name: string,
      version: string
    },
    value: {
      name: 'repro-app-myworkr',
      version: '0.1.0'
    }
  }
});
//! defines the environment configuration for the application
const environmentConfig = configInjector.chain({
  REDIS_URL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('REDIS_URL')
  },
  PROTOCOL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('PROTOCOL')
  },
  HOST: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('HOST')
  },
  PORT: {
    lifetime: Lifetime.Singleton,
    type: number,
    value: Number(getEnvVar('PORT'))
  },
  VERSION: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('VERSION') ?? 'v1'
  },
  DOCS_PATH: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('DOCS_PATH') ?? '/docs'
  },
  OTEL_SERVICE_NAME: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('OTEL_SERVICE_NAME')
  },
  OTEL_LEVEL: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('OTEL_LEVEL') || 'info'
  },
  OTEL_EXPORTER_OTLP_ENDPOINT: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('OTEL_EXPORTER_OTLP_ENDPOINT')
  },
  QUEUE_NAME: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('QUEUE_NAME')
  },
  HMAC_SECRET_KEY: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('HMAC_SECRET_KEY')
  },
  ENCRYPTION_KEY: {
    lifetime: Lifetime.Singleton,
    type: string,
    value: getEnvVar('ENCRYPTION_KEY')
  }
});
//! defines the runtime dependencies for the application
const runtimeDependencies = environmentConfig.chain({
  OtelCollector: {
    lifetime: Lifetime.Singleton,
    type: OpenTelemetryCollector,
    factory: ({ OTEL_SERVICE_NAME, OTEL_LEVEL }) =>
      new OpenTelemetryCollector(
        OTEL_SERVICE_NAME,
        OTEL_LEVEL || 'info',
        metrics
      )
  },
  EventEncryptor: {
    lifetime: Lifetime.Singleton,
    type: FieldEncryptor,
    factory: ({ ENCRYPTION_KEY }) => new FieldEncryptor(ENCRYPTION_KEY)
  },
  WorkerOptions: {
    lifetime: Lifetime.Singleton,
    type: BullMqWorkerSchemas({ validator: SchemaValidator() }),
    factory: ({ REDIS_URL }) => ({
      backoffType: 'exponential' as const,
      queueOptions: { connection: { url: REDIS_URL } },
      retries: 3,
      interval: 5e3
    })
  }
});
//! defines the service dependencies for the application
const serviceDependencies = runtimeDependencies.chain({
  MyworkrService: {
    lifetime: Lifetime.Scoped,
    type: BaseMyworkrService,
    factory: ({ WorkerProducer, OtelCollector }) =>
      new BaseMyworkrService(WorkerProducer, OtelCollector)
  },
  WorkerProducer: {
    lifetime: Lifetime.Scoped,
    type: EncryptingWorkerProducer,
    factory: ({ QUEUE_NAME, WorkerOptions, EventEncryptor }, context) =>
      new EncryptingWorkerProducer(
        new BullMqWorkerProducer(QUEUE_NAME, WorkerOptions),
        EventEncryptor,
        (context?.tenantId as string) ?? ''
      )
  },
  WorkerConsumer: {
    lifetime: Lifetime.Scoped,
    type: function_(
      [
        type<WorkerProcessFunction<MyworkrEventRecord>>(),
        type<WorkerFailureHandler<MyworkrEventRecord>>()
      ],
      type<BullMqWorkerConsumer<EncryptedEventEnvelope, BullMqWorkerOptions>>()
    ),
    factory:
      ({ QUEUE_NAME, WorkerOptions, EventEncryptor }) =>
      (
        processEventsFunction: WorkerProcessFunction<MyworkrEventRecord>,
        failureHandler: WorkerFailureHandler<MyworkrEventRecord>
      ) =>
        new BullMqWorkerConsumer(
          QUEUE_NAME,
          WorkerOptions,
          withDecryption<MyworkrEventRecord>(
            processEventsFunction,
            EventEncryptor
          ),
          withDecryptionFailureHandler<MyworkrEventRecord>(
            failureHandler,
            EventEncryptor
          )
        )
  }
});
//! validates the configuration and returns the dependencies for the application
export const createDependencyContainer = (envFilePath: string) => ({
  ci: serviceDependencies.validateConfigSingletons(envFilePath),
  tokens: serviceDependencies.tokens()
});
