pub(crate) const DIRS_TO_IGNORE: &[&str] = &[
    "node_modules",
    "assets",
    "patches",
    ".git",
    ".github",
    ".vscode",
    "monitoring",
    "core",
    "universal-sdk",
];

pub(crate) const DOCKER_SERVICES_TO_IGNORE: &[&str] = &[
    "redis",
    "postgres",
    "mysql",
    "mariadb",
    "sqlite",
    "better-sqlite",
    "libsql",
    "mssql",
    "mongodb",
    "rabbitmq",
    "tempo",
    "loki",
    "prometheus",
    "grafana",
    "otel-collector",
    "redis",
    "postgresql",
    "mysql",
    "mariadb",
    "sqlite",
    "better-sqlite",
    "libsql",
    "mssql",
    "mongodb",
    "rabbitmq",
    "tempo",
    "loki",
    "prometheus",
    "grafana",
    "otel-collector",
];

pub(crate) const RUNTIME_PROJECTS_TO_IGNORE: &[&str] = &[
    "core",
    "monitoring",
    "universal-sdk",
];