/**
 * Generated by ForkLaunch
 * File: universalSdk.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */


import { universalSdk } from "@forklaunch/universal-sdk";

