FROM oven/bun:latest

WORKDIR /app

# Copy source code
COPY . .
RUN mv package.bun.json package.json

# Install curl for health checks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN bun install

# Build TypeScript code
RUN bun run build
