FROM node:23-alpine

WORKDIR /app

# Copy source code
COPY . .

# Install dependencies
RUN npm install -g pnpm
RUN apk add --no-cache git
RUN apk add --no-cache curl

# Install dependencies with proper Node.js settings
RUN pnpm install

# Build TypeScript code
RUN pnpm build