packages:
  - core
  - monitoring
  - billing
  - iam
  - sample-worker
  - implementations/billing/base
  - implementations/iam/base
  - interfaces/billing
  - interfaces/iam

overrides:
  '@forklaunch/common': link:../framework/common
  '@forklaunch/validator': link:../framework/validator
  '@forklaunch/core': link:../framework/core
  '@forklaunch/express': link:../framework/express
  '@forklaunch/hyper-express': link:../framework/hyper-express
  '@forklaunch/universal-sdk': link:../framework/universal-sdk
