/**
 * Generated by ForkLaunch
 * File: vitest.config.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    exclude: ['**/lib/**', '**/dist/**', '**/node_modules/**']
  }
});