[package]
name = "forklaunch"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.21", features = ["cargo"] }
futures-io = "0.3.31"
indexmap = { version = "2.6.0", features = ["serde"] }
paste = "1.0.15"
pathdiff = "0.2.2"
ramhorns = "1.0.1"
rcgen = "0.13.2"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_yml = "0.0.12"
toml = "0.8.19"
