[package]
name = "forklaunch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.21", features = ["cargo"] }
futures-io = "0.3.31"
ramhorns = "1.0.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
