# This is a dummy file to run the depcheck and other useful commands.
id = "27e13038-212c-4989-99b0-d970cc30fe4e"
cli_version = "0.1.0"
app_name = "forklaunch-framework"
app_description = "Blueprint for forklaunch services"
linter="eslint"
formatter="prettier"
validator = "none"
http_framework = "none"
runtime = "none"
test_framework = "none"
author = "Rohin Bhargava"
license = "MIT"

[[projects]]
type = "Library"
name = "core"
description = ""

[[projects]]
type = "Library"
name = "monitoring"
description = ""

[[projects]]
type = "Service"
name = "billing-base"
description = ""
routers = [
    "billingPortal",
    "checkoutSession",
    "paymentLink",
    "plan",
    "subscription",
]

[projects.resources]
database = "postgresql"

[[projects]]
type = "Service"
name = "iam-base"
description = ""
routers = [
    "organization",
    "permission",
    "role",
    "user",
]

[projects.resources]
database = "postgresql"

[[projects]]
type = "Service"
name = "iam-better-auth"
description = ""
routers = [
    "organization",
    "permission",
    "role",
    "user",
]

[projects.resources]
database = "postgresql"


[[projects]]
type = "Worker"
name = "sample-worker"
description = ""
routers = ["sample-worker"]

[projects.resources]
database = "postgresql"

[project_peer_topology]
forklaunch_framework = [
    "core",
    "monitoring",
    "billing-base",
    "iam-base",
    "iam-better-auth",
    "sample-worker",
]
