FROM oven/bun:1

WORKDIR /app

# Copy source code
COPY . .
RUN mv package.bun.json package.json

# Install dependencies
RUN bun install

# Build TypeScript code
RUN bun run build

# Start the app
ENTRYPOINT ["bash", "../scripts/startup.dev.bun.sh", ".env.docker"]
