volumes:
  forklaunch-postgres-data:
    driver: local

networks:
  forklaunch-network:
    name: forklaunch-network
    driver: bridge

services:
  tempo:
    image: grafana/tempo:latest
    ports:
      - '3200:3200'
      - '4317:4317'
    networks:
      - forklaunch-network
    volumes:
      - './monitoring/tempo.yaml:/etc/tempo.yaml'
    command: '-config.file=/etc/tempo.yaml'

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    networks:
      - forklaunch-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    networks:
      - forklaunch-network
    volumes:
      - './monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - forklaunch-network
    volumes:
      - './monitoring/grafana-provisioning/datasources:/etc/grafana/provisioning/datasources'
      - './monitoring/grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards'

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - '4318:4318'
      - '8889:8889'
    networks:
      - forklaunch-network
    volumes:
      - './monitoring/otel-collector-config.yaml:/etc/otel-collector-config.yaml'
    command: '--config=/etc/otel-collector-config.yaml'

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: forklaunch-pg
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - forklaunch-network
    volumes:
      - forklaunch-postgres-data:/var/lib/postgresql/forklaunch/data

  # client:
  #   hostname: client
  #   container_name: forklaunch-client
  #   restart: always
  #   build:
  #     context: ./client
  #     dockerfile: ./Dockerfile.dev
  #   image: forklaunch_client:latest
  #   environment:
  #     ENV: development
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - forklaunch-network
  #   volumes:
  #     - ./client/src:/app/src

  iam:
    hostname: iam
    container_name: forklaunch-iam-${RUNTIME}
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.${RUNTIME}.dev
    environment:
      ENV: development
      PORT: 8000
      DB_NAME: forklaunch-dev
      DB_HOST: postgres
      DB_USER: postgresql
      DB_PASSWORD: postgresql
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    networks:
      - forklaunch-network

    working_dir: /app/iam

  billing:
    hostname: billing
    container_name: forklaunch-billing-${RUNTIME}
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.${RUNTIME}.dev
    environment:
      ENV: development
      PORT: 8001
      DB_NAME: forklaunch-dev
      DB_HOST: postgres
      DB_USER: postgresql
      DB_PASSWORD: postgresql
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - 8001:8001
    networks:
      - forklaunch-network
    working_dir: /app/billing

  redis:
    image: redis/redis-stack-server:latest
    container_name: forklaunch-redis
    depends_on:
      - postgres
    restart: always
    ports:
      - '6379:6379'
    networks:
      - forklaunch-network
