/**
 * Generated by ForkLaunch
 * File: jwks.entity.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { SqlBaseEntity } from '@forklaunch/blueprint-core';
import { Entity, Property } from '@mikro-orm/core';

@Entity()
export class Jwks extends SqlBaseEntity {
  /**
   * The public part of the web key
   */
  @Property()
  publicKey!: string;

  /**
   * The private part of the web key
   */
  @Property()
  privateKey!: string;
}
