/**
 * Generated by ForkLaunch
 * File: seed.data.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { RequiredEntityData } from '@mikro-orm/core';
import { OrganizationStatus } from '../domain/enum/organizationStatus.enum';
import { Organization, Permission, Role } from '../persistence/entities';
import { User } from '../persistence/entities/user.entity';
import { Account } from './entities/account.entity';
import { Session } from './entities/session.entity';
import { Verification } from './entities/verification.entity';
//! Begin seed data
export const permission = {
  id: 'e7e2d2da-1f6a-4657-bb7d-221b1a5f3f6a',
  slug: 'test',
  createdAt: new Date(),
  updatedAt: new Date()
} satisfies RequiredEntityData<Permission>;

export const role = {
  id: 'e7e2d2da-1f6a-4657-bb7d-221b1a5f3f6a',
  name: 'test',
  permissions: [permission.id],
  createdAt: new Date(),
  updatedAt: new Date()
} satisfies RequiredEntityData<Role>;

export const user = {
  id: 'e7e2d2da-1f6a-4657-bb7d-221b1a5f3f6a',
  email: 'test@test.com',
  emailVerified: true,
  name: 'test',
  firstName: 'Test',
  lastName: 'User',
  roles: [role.id],
  createdAt: new Date(),
  updatedAt: new Date()
} satisfies RequiredEntityData<User>;

export const organization = {
  name: 'Test',
  users: [user.id],
  subscription: 'test',
  domain: 'test.com',
  status: OrganizationStatus.ACTIVE,
  createdAt: new Date(),
  updatedAt: new Date()
} satisfies RequiredEntityData<Organization>;

export const account = {
  user: user.id,
  providerId: 'test',
  accountId: 'test',
  accessToken: 'test',
  refreshToken: 'test',
  accessTokenExpiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
  refreshTokenExpiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
  createdAt: new Date(),
  updatedAt: new Date()
} satisfies RequiredEntityData<Account>;

export const session = {
  user: user.id,
  token: 'test',
  expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
  ipAddress: '127.0.0.1',
  userAgent: 'test',
  createdAt: new Date(),
  updatedAt: new Date()
} satisfies RequiredEntityData<Session>;

export const verification = {
  identifier: 'test',
  value: 'test',
  expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
  createdAt: new Date(),
  updatedAt: new Date()
} satisfies RequiredEntityData<Verification>;
