/**
 * Generated by ForkLaunch
 * File: seed.data.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { EntityManager } from '@mikro-orm/core';
import { OrganizationStatus } from '../domain/enum/organizationStatus.enum';
import { Organization, Permission, Role } from '../persistence/entities';
import { User } from '../persistence/entities/user.entity';
import { Account } from './entities/account.entity';
import { Session } from './entities/session.entity';
import { Verification } from './entities/verification.entity';
//! Begin seed data
export const permission = async (em: EntityManager) =>
  Permission.create(
    {
      slug: 'test',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    em
  );
export const role = async (em: EntityManager) =>
  Role.create(
    {
      name: 'test',
      permissions: [await permission(em)],
      createdAt: new Date(),
      updatedAt: new Date()
    },
    em
  );
export const user = async (em: EntityManager) =>
  User.create(
    {
      email: 'test@test.com',
      emailVerified: true,
      name: 'test',
      firstName: 'Test',
      lastName: 'User',
      roles: [await role(em)],
      createdAt: new Date(),
      updatedAt: new Date()
    },
    em
  );
export const organization = async (em: EntityManager) =>
  Organization.create(
    {
      name: 'Test',
      users: [await user(em)],
      subscription: 'test',
      domain: 'test.com',
      status: OrganizationStatus.ACTIVE,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    em
  );
export const account = async (em: EntityManager) =>
  Account.create(
    {
      user: await user(em),
      providerId: 'test',
      accountId: 'test',
      accessToken: 'test',
      refreshToken: 'test',
      accessTokenExpiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
      refreshTokenExpiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    em
  );
export const session = async (em: EntityManager) =>
  Session.create(
    {
      user: await user(em),
      token: 'test',
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
      ipAddress: '127.0.0.1',
      userAgent: 'test',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    em
  );
export const verification = async (em: EntityManager) =>
  Verification.create(
    {
      identifier: 'test',
      value: 'test',
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
      createdAt: new Date(),
      updatedAt: new Date()
    },
    em
  );
