/* eslint-disable @typescript-eslint/no-unused-vars */
import { noop } from '@forklaunch/common';
import {
  OpenTelemetryCollector,
  sdkClient,
  sdkRouter
} from '@forklaunch/core/http';
import {
  forklaunchExpress,
  forklaunchRouter,
  handlers
} from '@forklaunch/hyper-express';
import {
  MiddlewareNext,
  Request,
  Response
} from '@forklaunch/hyper-express-fork';
import {
  array,
  date,
  file,
  number,
  optional,
  SchemaValidator,
  string,
  union,
  uuid
} from '@forklaunch/validator/zod';

const zodSchemaValidator = SchemaValidator();
const openTelemetryCollector = new OpenTelemetryCollector('test');

const forklaunchApplication = forklaunchExpress(
  zodSchemaValidator,
  openTelemetryCollector,
  {
    hosting: {
      workerCount: 2
    }
  }
);

const forklaunchRouterInstance = forklaunchRouter(
  '/testpath',
  zodSchemaValidator,
  openTelemetryCollector
);

const expressMiddleware = (
  req: Request,
  res: Response,
  next: MiddlewareNext
) => {
  noop(req, res, next);
  next();
};

const getHandler = handlers.get(
  zodSchemaValidator,
  '/test',
  {
    name: 'Test',
    summary: 'Test Summary',
    responses: {
      200: {
        file: file
      }
    }
  },
  expressMiddleware,
  (_req, res) => {
    res.status(200).send(
      new File(
        [
          `Hello World
This is a test file generated by the server.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies, justo a facilisis posuere, urna massa dictum nisi, eu hendrerit erat est a velit.

Curabitur dignissim, dolor ut consequat tincidunt, sapien velit sodales sem, et placerat nunc enim ornare enim. Vivamus at tristique risus, nec posuere elit. Donec at tristique massa, non maximus enim.

- Item 1: The quick brown fox jumps over the lazy dog.
- Item 2: Etiam eget ligula eu lectus lobortis condimentum.
- Item 3: Mauris accumsan, massa non consectetur hendrerit, erat urna scelerisque sapien, sed cursus augue magna a lorem.

Nulla facilisi. Proin facilisis, justo nec porttitor ullamcorper, nisi nibh dictum ex, eu suscipit erat enim in velit. Pellentesque a consequat nunc. 

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti.

End of file.`
        ],
        'test.txt',
        { type: 'text/plain' }
      )
    );
  }
);

const postHandler = handlers.post(
  zodSchemaValidator,
  '/test',
  {
    name: 'Test',
    summary: 'Test Summary',
    body: {
      f: string,
      m: union([array(number), string])
    },
    responses: {
      200: {
        contentType: 'text/event-stream',
        event: {
          id: string,
          data: {
            message: string
          }
        }
      }
    }
  },
  expressMiddleware,
  (req, res) => {
    res.status(200).sseEmitter(async function* () {
      try {
        for (let i = 0; i < 100; i++) {
          yield {
            id: i.toString(),
            data: {
              message: `Hello World ${req.body.f}`
            }
          };
          await new Promise((resolve) => setTimeout(resolve, 10));
        }
      } catch (e: unknown) {
        if (e instanceof Error) {
          res.status(500).send('There was an error');
        }
      }
      return;
    });
  }
);

const jsonPatchHandler = handlers.patch(
  zodSchemaValidator,
  '/test',
  {
    name: 'Test',
    summary: 'Test Summary',
    body: {
      f: string,
      h: uuid
    },
    responses: {
      200: {
        json: {
          f: {
            g: array(date)
          }
        }
      }
    }
  },
  expressMiddleware,
  (req, res) => {
    res.status(200).json({ f: { g: [new Date(), new Date()] } });
  }
);

const multipartHandler = handlers.post(
  zodSchemaValidator,
  '/test/multipart',
  {
    name: 'Test',
    summary: 'Test Summary',
    body: {
      multipartForm: {
        f: string,
        g: file
      }
    },
    responses: {
      200: {
        text: string
      }
    }
  },
  expressMiddleware,
  async (req, res) => {
    res.status(200).send(`${req.body.f} ${await req.body.g.text()}`);
  }
);

const urlEncodedFormHandler = handlers.post(
  zodSchemaValidator,
  '/test/url-encoded-form',
  {
    name: 'Test',
    summary: 'Test Summary',
    body: {
      urlEncodedForm: {
        f: string,
        h: optional(number)
      }
    },
    responses: {
      200: {
        contentType: 'custom/content',
        schema: {
          a: string
        }
      }
    }
  },
  expressMiddleware,
  (req, res) => {
    res.status(200).json({ a: `${req.body.f}` });
  }
);

const getTest = forklaunchRouterInstance.get('/test', getHandler);
const postTest = forklaunchRouterInstance.post('/test', postHandler);
const jsonPatchTest = forklaunchRouterInstance.patch('/test', jsonPatchHandler);
const multipartTest = forklaunchRouterInstance.post(
  '/test/multipart',
  multipartHandler
);
const urlEncodedFormTest = forklaunchRouterInstance.post(
  '/test/url-encoded-form',
  urlEncodedFormHandler
);

forklaunchApplication.use(forklaunchRouterInstance);

const filePostHandler = handlers.post(
  zodSchemaValidator,
  '/test/file',
  {
    name: 'Test File Upload + Download',
    summary: 'Returns a file',
    body: file,
    responses: {
      200: file
    }
  },
  expressMiddleware,
  (req, res) => {
    res.status(200).send(req.body);
  }
);

const flRouter = forklaunchRouterInstance
  .get('/test', getHandler)
  .post('/test', postHandler)
  .patch('/test', jsonPatchHandler)
  .post('/test/multipart', multipartHandler)
  .post('/test/url-encoded-form', urlEncodedFormHandler)
  .post('/test/file', filePostHandler);

const flNestedRouter = forklaunchRouter(
  '/nested',
  zodSchemaValidator,
  openTelemetryCollector
)
  .get('/test', getHandler)
  .post('/test', postHandler);

const sdkRoutes = flRouter.use(flNestedRouter);
forklaunchApplication.use(sdkRoutes);

const sampleController = {
  get: getHandler,
  post: postHandler,
  patch: jsonPatchHandler,
  multipart: multipartHandler
};
const sampleController2 = {
  urlEncodedForm: urlEncodedFormHandler,
  file: filePostHandler
};

const sampleSdkRouter = sdkRouter(
  zodSchemaValidator,
  sampleController,
  sdkRoutes
);

const sampleSdkRouter2 = sdkRouter(
  zodSchemaValidator,
  sampleController2,
  sdkRoutes
);

export const sampleSdkClient = sdkClient(zodSchemaValidator, {
  sample: {
    path: {
      a: {
        b: sampleSdkRouter
      }
    },
    c: {
      d: sampleSdkRouter2
    }
  }
});

export const sampleSdkClient2 = sdkClient(zodSchemaValidator, {
  sample: {
    path: {
      a: {
        b: sdkRoutes
      }
    }
  }
});

forklaunchApplication.get(
  '/alfalfa',
  {
    name: 'Test',
    summary: 'Test',
    responses: {
      200: string
    }
  },
  (req, res) => {
    res.status(200).send('Hello World');
  }
);

export function start() {
  const port = Number(process.env.PORT) || 6937;
  return forklaunchApplication.listen(port, () => {
    console.log(`server started on ${port}`);
  });
}

// Only run the server if this script is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const port = Number(process.env.PORT) || 6937;
  forklaunchApplication.listen(port, () => {
    console.log(`server started on ${port}`);
  });
}

export type SDK = {
  getTest: typeof getTest;
  postTest: typeof postTest;
  jsonPatchTest: typeof jsonPatchTest;
  multipartTest: typeof multipartTest;
  urlEncodedFormTest: typeof urlEncodedFormTest;
};

// Temporary shim for supporting TSGO experimental compiler
import type * as uWs from 'uWebSockets.js';
type TSGOShim = uWs.us_listen_socket;
