/**
 * Generated by ForkLaunch
 * File: metricsDefinitions.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import { metricsDefinitions } from '@forklaunch/core/http';

export type Metrics = typeof metrics;

export const metrics = metricsDefinitions({
  customMetric: 'counter'
});