name: Build Framework

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'framework/**'
  pull_request:
    paths:
      - 'framework/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.1.0

      - name: Install system dependencies
        run: apt-get update && apt-get install -y git libatomic1

      - name: Install dependencies
        working-directory: ./framework
        run: pnpm install

      - name: Build framework
        working-directory: ./framework
        run: pnpm build

      - name: Run tests
        working-directory: ./framework
        run: pnpm test
