name: Build Framework

on:
  push:
    branches:
      - main
    paths:
      - 'framework/**'
  pull_request:
    paths:
      - 'framework/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install git
        run: apt-get update && apt-get install -y git

      - name: Install dependencies
        working-directory: ./framework
        run: pnpm install

      - name: Build framework
        working-directory: ./framework
        run: pnpm build

      - name: Run tests
        working-directory: ./framework
        run: pnpm test
