name: Build Packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        working-directory: ./packages
        run: pnpm install

      - name: Build packages
        working-directory: ./packages
        run: pnpm build
