name: CLI Tests

on:
  push:
    branches:
      - main
    paths:
      - "cli/**"
  pull_request:
    paths:
      - "cli/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('cli/Cargo.lock') }}

      - name: Run CLI tests
        working-directory: ./cli
        run: cargo test --verbose
