name: E2E Tests

on:
  push:
    branches:
      - main
    paths:
      - 'cli/**'
  pull_request:
    paths:
      - 'cli/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build project
      working-directory: ./cli
      run: cargo build

    - name: Create .forklaunch directory
      run: mkdir -p ~/.forklaunch

    - name: Create token file
      run: touch ~/.forklaunch/token

    - name: Find and run all test scripts
      working-directory: ./cli/tests
      run: |
        for test_script in *.sh; do
          if [ -f "$test_script" ]; then
            echo "Running test: $test_script"
            ./$test_script
          fi
        done

