/**
 * Generated by ForkLaunch
 * File: lib.ts
 * This is an auto-generated file. Modifications are encouraged but may inhibit automated upgrades.
 */

import type { BillingApiClient } from '@forklaunch/blueprint-billing-base';
import type { IamApiClient } from '@forklaunch/blueprint-iam-base';
import type { IamApiClient as IamBetterAuthApiClient } from '@forklaunch/blueprint-iam-better-auth';
import type { SampleWorkerApiClient } from '@forklaunch/blueprint-sample-worker';
import { universalSdk } from '@forklaunch/universal-sdk';
import { createAuthClient } from 'better-auth/client';

export type ForklaunchPlatformUniversalSdk = {
  iam: IamApiClient;
  billing: BillingApiClient;
  sampleWorker: SampleWorkerApiClient;
  iamBetterAuth: {
    betterAuth: ReturnType<typeof createAuthClient>;
    forklaunch: IamBetterAuthApiClient;
  };
};

export const forklaunchPlatformUniversalSdk = async ({
  iamHost,
  billingHost,
  sampleWorkerHost,
  iamBetterAuthHost
}: {
  iamHost: string;
  billingHost: string;
  sampleWorkerHost: string;
  iamBetterAuthHost: string;
}): Promise<ForklaunchPlatformUniversalSdk> => ({
  iam: await universalSdk<IamApiClient>({
    host: iamHost,
    registryOptions: {
      path: 'api/v1/openapi'
    }
  }),
  billing: await universalSdk<BillingApiClient>({
    host: billingHost,
    registryOptions: {
      path: 'api/v1/openapi'
    }
  }),
  sampleWorker: await universalSdk<SampleWorkerApiClient>({
    host: sampleWorkerHost,
    registryOptions: {
      path: 'api/v1/openapi'
    }
  }),
  iamBetterAuth: {
    betterAuth: createAuthClient({
      baseURL: iamBetterAuthHost
    }),
    forklaunch: await universalSdk<IamBetterAuthApiClient>({
      host: iamBetterAuthHost,
      registryOptions: {
        path: 'api/v1/openapi'
      }
    })
  }
});
